const path=require('node:path'); const fs=require('node:fs');
const express=require('express'); const helmet=require('helmet'); const cookieParser=require('cookie-parser'); const Database=require('better-sqlite3');
const {createSecurity,verifyPassword}=require('./src/security');
const {debtorsPdf,timesheetPdf,reminderPdf,certificatePdf}=require('./src/documents');

const app=express(); const port=Number(process.env.PORT||3000);
const inherited=path.resolve(__dirname,'../storage/ast-manager.sqlite3');
const local=path.resolve(__dirname,'storage/ast-manager.sqlite3'); const dbPath=process.env.AST_DB_PATH|| (fs.existsSync(inherited)?inherited:local);
fs.mkdirSync(path.dirname(dbPath),{recursive:true}); const db=new Database(dbPath); db.pragma('foreign_keys=ON'); db.pragma('journal_mode=WAL'); db.pragma('busy_timeout=10000');
db.exec(`CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY,name TEXT NOT NULL,email TEXT NOT NULL COLLATE NOCASE UNIQUE,password_hash TEXT NOT NULL,role TEXT NOT NULL,active INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,last_login_at TEXT); CREATE TABLE IF NOT EXISTS app_settings(setting_key TEXT PRIMARY KEY,setting_value TEXT NOT NULL DEFAULT '',updated_at TEXT NOT NULL);`);
const security=createSecurity(db);
app.set('trust proxy',1); app.use(helmet({contentSecurityPolicy:{directives:{defaultSrc:["'self'"],styleSrc:["'self'","'unsafe-inline'"],imgSrc:["'self'","data:"]}}}));
app.use(express.urlencoded({extended:false,limit:'1mb'})); app.use(cookieParser()); app.use('/assets',express.static(path.join(__dirname,'public'),{maxAge:'1h'}));

const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const q=(sql,args=[])=>db.prepare(sql).all(...args); const one=(sql,args=[])=>db.prepare(sql).get(...args);
const settings=()=>Object.fromEntries(q('SELECT setting_key,setting_value FROM app_settings').map(r=>[r.setting_key,r.setting_value]));
const nav=[['home','Übersicht'],['invoices','Debitoren'],['reminders','Mahnungen'],['timesheets','Stundennachweis'],['certificates','Zeugnisse'],['applications','Bewerbungen'],['salary','Lohnausweise'],['settings','Einstellungen']];
function shell(user,page,title,body){return `<!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} · AST</title><link rel="stylesheet" href="/assets/app.css"></head><body><aside><div class="brand">AST<small>VERWALTUNG</small></div><nav>${nav.map(([key,label])=>`<a class="${page===key?'active':''}" href="/?page=${key}">${esc(label)}</a>`).join('')}</nav><div class="account">${esc(user.name)}<small>${esc(user.role)}</small><form method="post" action="/logout"><input type="hidden" name="csrf" value="${esc(user.csrf)}"><button>Abmelden</button></form></div></aside><main><header><div><h1>${esc(title)}</h1><p>Gemeinsamer Datenstand von Desktop und Web</p></div><span class="badge">Online</span></header>${body}</main></body></html>`;}
function login(message=''){return `<!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>AST Manager</title><link rel="stylesheet" href="/assets/app.css"></head><body class="login"><form class="login-card" method="post" action="/login"><div class="brand dark">AST<small>VERWALTUNG</small></div><h1>Anmelden</h1>${message?`<p class="error">${esc(message)}</p>`:''}<label>E-Mail<input type="email" name="email" required autofocus></label><label>Passwort<input type="password" name="password" required></label><button class="primary">Anmelden</button></form></body></html>`;}
function table(headers,rows){return `<div class="table-wrap"><table><thead><tr>${headers.map(x=>`<th>${esc(x)}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.map(row=>`<tr>${row.map(x=>`<td>${esc(x)}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="${headers.length}" class="empty">Keine Einträge vorhanden.</td></tr>`}</tbody></table></div>`;}
function card(title,value,hint){return `<section class="metric"><small>${esc(title)}</small><strong>${esc(value)}</strong><span>${esc(hint)}</span></section>`;}
const requireUser=(req,res,next)=>{req.user=security.current(req); if(!req.user)return res.status(401).send(login()); next();};
app.get('/health',(req,res)=>res.json({ok:true,service:'AST Manager',database:fs.existsSync(dbPath)}));
app.post('/login',(req,res)=>{const user=one('SELECT * FROM users WHERE lower(email)=lower(?) AND active=1',[String(req.body.email||'').trim()]); if(!user||!verifyPassword(String(req.body.password||''),user.password_hash))return res.status(401).send(login('E-Mail oder Passwort ist nicht korrekt.')); security.login(res,user.id); db.prepare('UPDATE users SET last_login_at=? WHERE id=?').run(new Date().toISOString(),user.id); res.redirect('/');});
app.post('/logout',requireUser,(req,res)=>{if(!security.verifyCsrf(req,req.user))return res.status(400).send('Sitzung abgelaufen.'); security.logout(req,res); res.redirect('/');});
app.get('/',requireUser,(req,res)=>{const page=String(req.query.page||'home'); let title='Übersicht',body='';
 if(page==='home'){const inv=one('SELECT COALESCE(SUM(amount-paid_amount),0) open,COUNT(*) count FROM invoices')||{open:0,count:0}; const emp=one('SELECT COUNT(*) count FROM employees WHERE active=1')||{count:0}; body=`<div class="metrics">${card('Noch zu erhalten',`CHF ${Number(inv.open).toFixed(2)}`,'Offene Rechnungen')}${card('Rechnungen',inv.count,'Gesamter Datenstand')}${card('Team',emp.count,'Aktive Mitarbeitende')}</div><section class="panel"><h2>AST Manager Web</h2><p>Die Node.js-Fassung verwendet dieselbe zentrale Datenbasis wie die Desktop-Synchronisation.</p></section>`;}
 else if(page==='invoices'){title='Debitoren';const rows=q('SELECT * FROM invoices ORDER BY invoice_date DESC,id DESC');body=`<div class="actions"><a class="button" href="/exports/debtors.pdf">PDF exportieren</a><a class="button secondary" href="/exports/debtors.csv">CSV exportieren</a></div>${table(['Rechnung','Kunde','Datum','Fällig','Betrag','Bezahlt','Offen','Bemerkung'],rows.map(r=>[r.invoice_number,r.customer,r.invoice_date,r.due_date,Number(r.amount).toFixed(2),Number(r.paid_amount).toFixed(2),Number(r.amount-r.paid_amount).toFixed(2),r.notes]))}`;}
 else if(page==='reminders'){title='Mahnungen';const rows=q('SELECT * FROM reminders ORDER BY reminder_date DESC,id DESC');body=table(['Datum','Kunde','Rechnung','Stufe','Betrag','Status','PDF'],rows.map(r=>[r.reminder_date,r.customer,r.invoice_number,r.level,Number(r.amount).toFixed(2),r.status,`/exports/reminder/${r.id}.pdf`]));}
 else if(page==='timesheets'){title='Stundennachweis';const rows=q('SELECT t.*,e.first_name,e.last_name FROM time_entries t JOIN employees e ON e.id=t.employee_id ORDER BY work_date DESC');body=table(['Datum','Mitarbeiter','Arbeitszeit','Grund','Bemerkung'],rows.map(r=>[r.work_date,`${r.first_name} ${r.last_name}`,`${Number(r.hours).toFixed(2)} h`,r.reason,r.notes]));}
 else if(page==='certificates'){title='Zeugnisse';const rows=q('SELECT c.*,e.first_name,e.last_name FROM certificates c JOIN employees e ON e.id=c.employee_id ORDER BY reference_date DESC');body=table(['Mitarbeiter','Art','Datum','Status','PDF'],rows.map(r=>[`${r.first_name} ${r.last_name}`,r.certificate_type,r.reference_date,r.status,`/exports/certificate/${r.id}.pdf`]));}
 else if(page==='applications'){title='Bewerbungen';const rows=q('SELECT * FROM applications ORDER BY received_date DESC,id DESC');body=table(['Eingang','Name','Bewerbung für','Beurteilung','Ort','Kontakt'],rows.map(r=>[r.received_date,r.applicant_name,r.application_type,r.rating,r.city,r.email]));}
 else if(page==='salary'){title='Lohnausweise';const rows=q('SELECT s.*,e.first_name,e.last_name FROM salary_certificates s JOIN employees e ON e.id=s.employee_id ORDER BY tax_year DESC');body=table(['Jahr','Mitarbeiter','Bruttolohn','Status'],rows.map(r=>[r.tax_year,`${r.first_name} ${r.last_name}`,Number(r.gross_salary).toFixed(2),r.status]));}
 else if(page==='settings'){title='Einstellungen';const rows=q('SELECT name,email,role,active,last_login_at FROM users ORDER BY name');body=`<section class="panel"><h2>Benutzerverwaltung</h2>${table(['Name','E-Mail','Rolle','Status','Letzte Anmeldung'],rows.map(r=>[r.name,r.email,r.role,r.active?'Aktiv':'Inaktiv',r.last_login_at||'–']))}</section>`;}
 else return res.redirect('/'); res.send(shell(req.user,page,title,body));});
app.get('/exports/debtors.pdf',requireUser,(req,res)=>debtorsPdf(res,q('SELECT * FROM invoices ORDER BY invoice_date DESC')));
app.get('/exports/debtors.csv',requireUser,(req,res)=>{const rows=q('SELECT * FROM invoices ORDER BY invoice_date DESC');res.type('text/csv').attachment('Debitoren.csv').send('\ufeffRechnung;Kunde;Datum;Fällig;Betrag;Bezahlt;Offen;Bemerkung\r\n'+rows.map(r=>[r.invoice_number,r.customer,r.invoice_date,r.due_date,r.amount,r.paid_amount,r.amount-r.paid_amount,r.notes].map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(';')).join('\r\n'));});
app.get('/exports/timesheet/:employee/:year.pdf',requireUser,(req,res)=>{const employee=one('SELECT * FROM employees WHERE id=?',[req.params.employee]);if(!employee)return res.sendStatus(404);timesheetPdf(res,employee,req.params.year,q("SELECT * FROM time_entries WHERE employee_id=? AND substr(work_date,1,4)=? ORDER BY work_date",[employee.id,String(req.params.year)]));});
app.get('/exports/reminder/:id.pdf',requireUser,(req,res)=>{const row=one('SELECT * FROM reminders WHERE id=?',[req.params.id]);if(!row)return res.sendStatus(404);reminderPdf(res,row,settings());});
app.get('/exports/certificate/:id.pdf',requireUser,(req,res)=>{const row=one('SELECT * FROM certificates WHERE id=?',[req.params.id]);if(!row)return res.sendStatus(404);const employee=one('SELECT * FROM employees WHERE id=?',[row.employee_id]);certificatePdf(res,row,employee,settings());});
app.use((err,req,res,next)=>{console.error(err);res.status(500).send('Die Aktion konnte nicht abgeschlossen werden.');});
app.listen(port,'0.0.0.0',()=>console.log(`AST Manager listening on ${port}; database ${dbPath}`));
